-- 2022년 1월의 도서 판매 데이터를 기준으로 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 
SELECT T3.AUTHOR_ID, T3.AUTHOR_NAME, T2.CATEGORY, SUM(T1.SALES) TOTAL_SALES
  FROM (
    SELECT A.BOOK_ID, B.PRICE, (B.PRICE * SUM(SALES)) SALES 
      FROM BOOK_SALES A, BOOK B
     WHERE A.BOOK_ID = B.BOOK_ID
       AND TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
     GROUP BY A.BOOK_ID, B.PRICE
  ) T1, BOOK T2, AUTHOR T3
 WHERE T1.BOOK_ID = T2.BOOK_ID
   AND T2.AUTHOR_ID = T3.AUTHOR_ID
 GROUP BY T3.AUTHOR_ID, T3.AUTHOR_NAME, T2.CATEGORY
 ORDER BY T3.AUTHOR_ID, T2.CATEGORY DESC
;
