/* (풀이 1)
SELECT A.USER_ID, A.PRODUCT_ID
  FROM (
  SELECT USER_ID, PRODUCT_ID, COUNT(*) CNT
    FROM ONLINE_SALE
   GROUP BY USER_ID, PRODUCT_ID) A
 WHERE A.CNT >= 2
 ORDER BY 1, 2 DESC; */
 
 -- 코드를 입력하세요
 SELECT USER_ID, PRODUCT_ID
   FROM ONLINE_SALE
  GROUP BY USER_ID, PRODUCT_ID
 HAVING COUNT(*) > 1
  ORDER BY 1, 2 DESC;