-- 코드를 입력하세요
SELECT A.PRODUCT_CODE, PD.PRICE * A.AMT AS SALES 
  FROM 
    (SELECT PRODUCT_CODE, SUM(OS.SALES_AMOUNT) AMT
      FROM PRODUCT P INNER JOIN OFFLINE_SALE OS ON P.PRODUCT_ID = OS.PRODUCT_ID
     GROUP BY PRODUCT_CODE) A INNER JOIN PRODUCT PD ON A.PRODUCT_CODE = PD.PRODUCT_CODE
 ORDER BY 2 DESC, 1; 
 