-- 코드를 입력하세요
SELECT T.ANIMAL_ID, T.NAME
  FROM (
    SELECT AO.ANIMAL_ID, AO.NAME
         , TRUNC(AO.DATETIME) - TRUNC(AI.DATETIME)
      FROM ANIMAL_OUTS AO LEFT JOIN ANIMAL_INS AI ON AO.ANIMAL_ID = AI.ANIMAL_ID
     WHERE AI.DATETIME IS NOT NULL
     ORDER BY 3 DESC
    ) T
WHERE ROWNUM <= 2
  
  