-- 코드를 입력하세요
SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
     , B.SCORE
  FROM REST_INFO A 
  INNER JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) SCORE
      FROM REST_REVIEW 
     GROUP BY REST_ID
  ) B ON A.REST_ID = B.REST_ID
 WHERE A.ADDRESS LIKE '서울%'
 ORDER BY SCORE DESC, FAVORITES DESC;