-- 코드를 입력하세요
SELECT T.YEAR, T.MONTH, T.GENDER, COUNT(T.USER_ID) USERS
  FROM (
    SELECT EXTRACT(YEAR FROM SALES_DATE) YEAR
         , EXTRACT(MONTH FROM SALES_DATE) MONTH
         , GENDER
         , B.USER_ID
      FROM ONLINE_SALE A 
     INNER JOIN USER_INFO B ON A.USER_ID = B.USER_ID
     WHERE B.GENDER IS NOT NULL
     GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE), GENDER, B.USER_ID
  ) T
 GROUP BY T.YEAR, T.MONTH, T.GENDER
 ORDER BY 1, 2, 3;