-- 코드를 입력하세요
SELECT A.CAR_ID, A.AVAILABILITY
  FROM (
    SELECT ROW_NUMBER() OVER(PARTITION BY CAR_ID ORDER BY CAR_ID) RNUM
         , CAR_ID
         , CASE WHEN TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-10-16'
                 AND TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-10-16'
                THEN '대여중'
                ELSE '대여 가능' END AS AVAILABILITY
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     ORDER BY CAR_ID DESC, 3 DESC
  ) A
 WHERE A.RNUM = 1
;