-- 코드를 입력하세요
SELECT T.NAME, T.DATETIME
  FROM (
    SELECT AI.ANIMAL_ID, AI.NAME, AI.DATETIME
         , TRUNC(SYSDATE) - TRUNC(AI.DATETIME)
      FROM ANIMAL_INS AI LEFT JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
     WHERE AO.DATETIME IS NULL
     ORDER BY 4 DESC
  ) T
 WHERE ROWNUM <= 3
 ;