-- 코드를 입력하세요
SELECT A.PRODUCT_ID, B.PRODUCT_NAME, (A.AMT * B.PRICE) TOTAL_SALES
  FROM (
    SELECT PRODUCT_ID
         , SUM(AMOUNT) AMT
      FROM FOOD_ORDER
     -- WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
     WHERE PRODUCE_DATE BETWEEN TO_DATE('20220501', 'YYYYMMDD')
       AND TO_DATE('20220531', 'YYYYMMDD')
     GROUP BY PRODUCT_ID
  ) A INNER JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
 ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID;