-- 7월 아이스크림 총 주문량 + 상반기의 아이스크림 총 주문량 => 상위 3개
SELECT A.FLAVOR
  FROM FIRST_HALF A
 INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
      FROM JULY 
     GROUP BY FLAVOR
 ) B ON A.FLAVOR = B.FLAVOR
 ORDER BY (A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
 FETCH FIRST 3 ROWS ONLY;