SELECT A.APNT_NO, B.PT_NAME, B.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
  FROM APPOINTMENT A, PATIENT B, DOCTOR C
 WHERE A.PT_NO = B.PT_NO
   AND A.MDDR_ID = C.DR_ID
   AND A.APNT_CNCL_YN = 'N'
   -- AND TO_CHAR(A.APNT_YMD, 'YYYYMMDD') = '20220413'
   AND A.APNT_YMD BETWEEN TO_DATE('2022-04-13', 'YYYY-MM-DD') 
   AND TO_DATE('2022-04-13 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
   AND A.MCDP_CD = 'CS'
 ORDER BY A.APNT_YMD;