-- 코드를 입력하세요
/*
SELECT TO_CHAR(DATETIME, 'HH24') HOUR, COUNT(ANIMAL_ID) COUNT
  FROM ANIMAL_OUTS 
 GROUP BY TO_CHAR(DATETIME, 'HH24')
 ORDER BY HOUR
*/
SELECT T.LV HOUR, NVL(A.COUNT, 0) COUNT
  FROM (
    SELECT (LEVEL - 1) LV
      FROM DUAL 
    CONNECT BY LEVEL < 25
     ) T LEFT JOIN (
     SELECT TO_CHAR(DATETIME, 'HH24') HOUR, COUNT(ANIMAL_ID) COUNT
      FROM ANIMAL_OUTS 
     GROUP BY TO_CHAR(DATETIME, 'HH24')
     ) A ON T.LV = A.HOUR
  ORDER BY 1;

