-- 코드를 입력하세요
SELECT T2.MEMBER_NAME
     , T1.REVIEW_TEXT
     , TO_CHAR(T1.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
  FROM REST_REVIEW T1
 INNER JOIN (
    SELECT A.MEMBER_ID, MEMBER_NAME, COUNT(REVIEW_ID) CNT
      FROM REST_REVIEW A, MEMBER_PROFILE B
     WHERE A.MEMBER_ID = B.MEMBER_ID
     GROUP BY A.MEMBER_ID, MEMBER_NAME
     ORDER BY CNT DESC
     FETCH FIRST 1 ROWS ONLY
 ) T2 ON T1.MEMBER_ID = T2.MEMBER_ID
 ORDER BY REVIEW_DATE, REVIEW_TEXT
;