-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(START_DATE, 'FMMM')) MONTH, CAR_ID, COUNT(HISTORY_ID) RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE CAR_ID IN (
    SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE TO_CHAR(START_DATE, 'YYYY-MM-DD') BETWEEN '2022-08-01' AND '2022-10-31'
     GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
  )
 GROUP BY TO_NUMBER(TO_CHAR(START_DATE, 'FMMM')), CAR_ID
HAVING TO_NUMBER(TO_CHAR(START_DATE, 'FMMM')) BETWEEN 8 AND 10
 ORDER BY 1, 2 DESC;