-- 코드를 입력하세요
SELECT T.CATEGORY, SUM(T.SALES) TOTAL_SALES
  FROM (
    SELECT CATEGORY, SALES
      FROM BOOK A, BOOK_SALES B
     WHERE A.BOOK_ID = B.BOOK_ID
       AND TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
    ) T
 GROUP BY T.CATEGORY
 ORDER BY 1;
