-- 코드를 입력하세요
SELECT T.CATEGORY, T.PRICE MAX_PRICE, A.PRODUCT_NAME
  FROM (
    SELECT CATEGORY, MAX(PRICE) PRICE
      FROM FOOD_PRODUCT
     WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
     GROUP BY CATEGORY
  ) T INNER JOIN FOOD_PRODUCT A ON T.CATEGORY = A.CATEGORY AND T.PRICE = A.PRICE
 ORDER BY 2 DESC;